
(function(){
const S={t:null,classes:[],attClass:'',attDate:'',marksClass:'',conv:'',hwFilter:'all',msgQuery:'',analyticsClass:'all'};
const $=id=>document.getElementById(id), txt=(id,v)=>{const e=$(id);if(e)e.textContent=v;};
const tUser=()=>{let u=JSON.parse(localStorage.getItem('vm_teacherUser')||'null');if(!u){const a=JSON.parse(localStorage.getItem('ssvm_auth')||'null');if(a?.role==='teacher'&&a.user){u=a.user;localStorage.setItem('vm_teacherUser',JSON.stringify(u));}}return u;};
const cLabel=x=>`${x.class}${x.section}`;
const parseClasses=v=>(v||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=>{const m=x.match(/(\d+)\s*([A-Z])/i);return m?{class:m[1],section:m[2].toUpperCase()}:null;}).filter(Boolean);
const students=()=>getData('vm_students').filter(s=>S.classes.some(c=>s.class===c.class&&s.section===c.section));
const byClass=k=>students().filter(s=>`${s.class}${s.section}`===k);
const today=()=>new Date().toISOString().split('T')[0];
const fmt=d=>d?new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'--';
const rel=t=>{if(!t)return'--';const diff=Date.now()-new Date(t).getTime();if(diff<6e4)return'Just now';if(diff<36e5)return`${Math.floor(diff/6e4)} min ago`;if(diff<864e5)return`${Math.floor(diff/36e5)} hr ago`;if(diff<6048e5)return`${Math.floor(diff/864e5)} days ago`;return fmt(t);};
const parseSizeMb=v=>{const raw=String(v||'0').toLowerCase().trim(); const n=parseFloat(raw); if(!Number.isFinite(n)) return 0; if(raw.includes('gb')) return n*1024; if(raw.includes('kb')) return n/1024; return n;};
const hw=()=>getData('vm_homework').filter(h=>h.teacherId===S.t.id||h.teacher===S.t.name||h.subject===S.t.subject);
const msgs=()=>getData('vm_messages').filter(m=>m.from===S.t.id||m.to===S.t.id);
const teacherAdminNotices=()=>getData('vm_notices').filter(n=>n.author==='Admin'&&['all','teachers'].includes(n.audience||'all'));
const notices=()=>getData('vm_notices').filter(n=>n.author===S.t.name||n.author===S.t.id||(n.author==='Admin'&&['all','teachers'].includes(n.audience||'all')));
const teacherNoticeSeenState=()=>getObj('vm_teacherNoticeSeen');
const saveTeacherNoticeSeen=id=>{const all=teacherNoticeSeenState(); all[id]=new Date().toISOString(); setData('vm_teacherNoticeSeen',all);};
const unseenAdminNoticeCount=()=>{const seen=teacherNoticeSeenState()[S.t.id]||''; return teacherAdminNotices().filter(n=>new Date(n.date||n.timestamp||0)>new Date(seen||0)).length;};
const materials=()=>{const all=getObj('vm_studyMaterials');const key=normalizeText(S.t.subject||'');return{all,key,list:all[key]||[]};};
const settings=()=>{const all=getObj('vm_teacherSettings');return all[S.t.id]||{emailNotifications:true,parentAlerts:false,taskReminders:true};};
const saveSettingsState=v=>{const all=getObj('vm_teacherSettings');all[S.t.id]=v;setData('vm_teacherSettings',all);};
const lessonPlans=()=>{const all=getObj('vm_teacherLessonPlans');return all[S.t.id]||[];};
const saveLessonPlans=v=>{const all=getObj('vm_teacherLessonPlans');all[S.t.id]=v;setData('vm_teacherLessonPlans',all);};
const attReg=()=>getObj('vm_teacherAttendanceRegister');
const attKey=(k,d)=>`${S.t.id}_${k}_${d}`;
const attRecord=(k,d)=>attReg()[attKey(k,d)]||{};
const setAttRecord=(k,d,r)=>{const all=attReg();all[attKey(k,d)]=r;setData('vm_teacherAttendanceRegister',all);};
const grade=m=>{m=Number(m)||0;return m>=90?'A+':m>=80?'A':m>=70?'B+':m>=60?'B':m>=50?'C':'F';};
async function persistTeacherKey(key,value){
if(typeof window.vmPersistKey==='function'){
const result=await window.vmPersistKey(key,value);
if(result?.syncedRemotely===false&&result.error)throw result.error;
return result;
}
setData(key,value);
return{storedLocally:true,syncedRemotely:false};
}
function ensureTeacherDemoData(){
const ss=students();
if(!ss.length)return;
const makeDate=offset=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().split('T')[0];};
const h=list=>setData('vm_homework',list), m=list=>setData('vm_messages',list), n=list=>setData('vm_notices',list), e=list=>setData('vm_examSchedule',list);
let homework=getData('vm_homework');
const teacherHomework=homework.filter(x=>x.teacherId===S.t.id||x.teacher===S.t.name||x.subject===S.t.subject);
if(teacherHomework.length<4){
const samples=[
{title:`${S.t.subject} Practice Set 1`,description:'Solve the worksheet and submit neat handwritten steps.',dueDate:makeDate(2),marks:15,status:'pending',submitted:false},
{title:`${S.t.subject} Revision Quiz`,description:'Prepare key formulas, definitions, and complete the quiz sheet.',dueDate:makeDate(4),marks:20,status:'pending',submitted:false},
{title:`${S.t.subject} Notebook Check`,description:'Complete class notes and highlight important keywords.',dueDate:makeDate(6),marks:10,status:'completed',submitted:true,submissionDate:makeDate(-1),obtainedMarks:9}
];
samples.forEach((sample,i)=>{
const target=ss[i%ss.length];
const cls=`${target.class}${target.section}`;
if(!homework.some(x=>x.studentId===target.id&&normalizeText(x.title)===normalizeText(sample.title))){
homework.unshift({id:`THW${Date.now()}${i}`,studentId:target.id,class:cls,subject:S.t.subject,teacher:S.t.name,teacherId:S.t.id,...sample});
}
});
h(homework);
}
let messages=getData('vm_messages');
const teacherMessages=messages.filter(x=>x.from===S.t.id||x.to===S.t.id);
if(teacherMessages.length<4){
ss.slice(0,3).forEach((student,i)=>{
const sampleSubject=[`Doubt in ${S.t.subject}`,`Project update for ${S.t.subject}`,`Need help with assignment`][i]||`${S.t.subject} follow-up`;
if(!messages.some(x=>x.from===student.id&&x.to===S.t.id&&normalizeText(x.subject)===normalizeText(sampleSubject))){
messages.push({id:`TMSG${Date.now()}${i}`,from:student.id,to:S.t.id,subject:sampleSubject,content:[`Ma'am, chapter 3 ke last questions me thoda confusion hai.`,`Sir, project draft ready hai. Kya aap kal review kar sakte hain?`,`Homework submit kar diya hai, please confirm once checked.`][i]||`Please review my ${S.t.subject} work.`,timestamp:new Date(Date.now()-(i+2)*36e5).toISOString(),read:i===0?false:true,type:'received'});
}
});
if(!messages.some(x=>x.from===S.t.id&&x.to===ss[0].id&&normalizeText(x.subject)===normalizeText(`Weekly ${S.t.subject} reminder`))){
messages.push({id:`TMSGOUT${Date.now()}`,from:S.t.id,to:ss[0].id,subject:`Weekly ${S.t.subject} reminder`,content:'Please revise the last two topics and bring your notebook for review in the next class.',timestamp:new Date(Date.now()-18e5).toISOString(),read:false,type:'sent'});
}
m(messages);
}
let notices=getData('vm_notices');
if(!notices.some(x=>x.author===S.t.name&&normalizeText(x.title)===normalizeText(`${S.t.subject} class test notice`))){
n([{id:`TN${Date.now()}`,title:`${S.t.subject} class test notice`,content:`Class test for ${S.t.subject} is scheduled this week. Students should revise recent chapters and bring required stationery.`,date:makeDate(1),type:'important',author:S.t.name,category:'classroom'},...notices]);
}
let mats=getObj('vm_studyMaterials');
const matKey=normalizeText(S.t.subject||'');
if(!Array.isArray(mats[matKey])||mats[matKey].length<3){
const existing=Array.isArray(mats[matKey])?mats[matKey]:[];
const samples=[
{id:`TMAT${Date.now()}1`,title:`${S.t.subject} Smart Notes`,type:'pdf',size:'1.8 MB',downloads:24},
{id:`TMAT${Date.now()}2`,title:`${S.t.subject} Worksheet Pack`,type:'pdf',size:'2.4 MB',downloads:17},
{id:`TMAT${Date.now()}3`,title:`${S.t.subject} Concept Revision Video`,type:'mp4',size:'42 MB',downloads:11}
];
samples.reverse().forEach(sample=>{if(!existing.some(x=>normalizeText(x.title)===normalizeText(sample.title)))existing.unshift(sample);});
mats[matKey]=existing;
setData('vm_studyMaterials',mats);
}
let plans=lessonPlans();
if(plans.length<2){
const classes=[...new Set(ss.map(x=>`${x.class}${x.section}`))];
[
{id:`LPD${Date.now()}1`,date:makeDate(1),classLabel:classes[0]||S.attClass,topic:`${S.t.subject} concept drill`,goal:'Concept mastery',duration:'45 min',mode:'Interactive board teaching',objective:'Strengthen core understanding through guided examples and board practice.',resources:'Presentation slides, board examples, oral recap',strategy:'Begin with recap questions, model 2 examples, pair practice, then guided correction.',assessment:'Use 5-minute exit ticket and notebook observation.',support:'Provide scaffold steps for hesitant learners and challenge problems for advanced students.',success:'Students can solve standard problems independently.'},
{id:`LPD${Date.now()}2`,date:makeDate(3),classLabel:classes[1]||classes[0]||S.attClass,topic:`${S.t.subject} assessment review`,goal:'Exam readiness',duration:'40 min',mode:'Revision and assessment',objective:'Discuss common mistakes and improve answer presentation.',resources:'Printed worksheet, peer discussion prompts',strategy:'Review most common errors, run peer correction, close with timed practice.',assessment:'Mini quiz and oral questioning during discussion.',support:'Seat mixed-ability pairs and keep extra prompts for weak learners.',success:'Students can explain errors and improve response quality.'}
].forEach(plan=>{if(!plans.some(x=>normalizeText(x.topic)===normalizeText(plan.topic)&&x.classLabel===plan.classLabel))plans.unshift(plan);});
saveLessonPlans(plans);
}
let register=attReg();
const firstClass=`${ss[0].class}${ss[0].section}`;
if(firstClass&&!register[attKey(firstClass,today())]){
register[attKey(firstClass,today())]=Object.fromEntries(byClass(firstClass).map((student,i)=>[student.id,i%4===0?'A':'P']));
setData('vm_teacherAttendanceRegister',register);
}
let exams=getData('vm_examSchedule');
if(!exams.some(x=>normalizeText(x.subject)===normalizeText(S.t.subject))){
e([{id:`TEX${Date.now()}`,examName:`${S.t.subject} Unit Test`,subject:S.t.subject,date:makeDate(5),time:'10:30 AM',room:'Room 204'},...exams]);
}
const teacherSettings=getObj('vm_teacherSettings');
if(!teacherSettings[S.t.id]){
teacherSettings[S.t.id]={emailNotifications:true,parentAlerts:true,taskReminders:true};
setData('vm_teacherSettings',teacherSettings);
}
}
function syncTopbar(){txt('teacherName',S.t.name);txt('teacherSubject',S.t.subject);txt('teacherTopbarMeta',`${S.t.subject} | ${S.t.class}`);txt('profileTeacherName',S.t.name);txt('profileTeacherSubject',S.t.subject);txt('profileTeacherId',S.t.id);txt('profileTeacherEmail',S.t.email||'--');txt('profileTeacherPhone',S.t.phone||'--');txt('profileTeacherExp',S.t.exp||'--');txt('profileTeacherClasses',S.t.class||'--');}
function openSection(id){document.querySelectorAll('.portal-nav a[data-section]').forEach(a=>a.classList.toggle('active',a.dataset.section===id));document.querySelectorAll('.portal-section').forEach(s=>s.classList.toggle('active',s.id===id));const a=document.querySelector(`.portal-nav a[data-section="${id}"]`);if(a){txt('portalTopbarTitle',a.textContent.trim());txt('teacherTopbarMeta',`${S.t.subject} | ${S.classes.length} assigned classes`);} if(id==='secNotices'){saveTeacherNoticeSeen(S.t.id); renderDash(); renderNotices();} $('teacherSidebar')?.classList.remove('open');}
function fillSelectors(){const opts=S.classes.map(c=>`<option value="${cLabel(c)}">Class ${c.class}-${c.section}</option>`).join('');['attendanceClassSelect','marksClassSelect','tpHomeworkClass','tpLessonClass'].forEach(id=>{const el=$(id);if(el)el.innerHTML=(id==='tpHomeworkClass'||id==='tpLessonClass'?'<option value="">Choose class</option>':'')+opts;}); if($('analyticsClassSelect')) $('analyticsClassSelect').innerHTML='<option value="all">All Classes</option>'+opts; if(!S.attClass&&S.classes[0])S.attClass=cLabel(S.classes[0]);if(!S.marksClass&&S.classes[0])S.marksClass=cLabel(S.classes[0]); if(!S.analyticsClass) S.analyticsClass='all'; $('attendanceClassSelect').value=S.attClass;$('marksClassSelect').value=S.marksClass;$('attendanceDate').value=S.attDate; if($('analyticsClassSelect')) $('analyticsClassSelect').value=S.analyticsClass; if($('tpLessonDate')) $('tpLessonDate').value=today();}
function fillMessageStudents(){$('tpMessageStudent').innerHTML='<option value="">Choose student</option>'+students().map(s=>`<option value="${s.id}">${s.name} - Class ${s.class}-${s.section}</option>`).join('');}
function renderDash(){const ss=students(), h=hw(), m=msgs(), marks=getObj('vm_marks'); const unread=m.filter(x=>x.to===S.t.id&&!x.read).length, adminUnread=unseenAdminNoticeCount(), totalNotif=unread+adminUnread; const vals=ss.map(s=>Number(marks[s.id]?.[S.t.subject])).filter(Number.isFinite); const avg=vals.length?(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1):'0.0'; txt('teacherWelcomeName',`Welcome back, ${S.t.name.split(' ')[0]}`); txt('teacherAssignedClasses',`Assigned classes: ${S.t.class||'--'}`); txt('teacherTodayDate',new Date().toLocaleDateString('en-IN',{weekday:'short',day:'2-digit',month:'short'})); txt('dashStudentCount',String(ss.length)); txt('dashHomeworkCount',String(h.filter(x=>!x.submitted).length)); txt('dashUnreadCount',String(unread)); txt('dashAverageScore',`${avg}%`); txt('teacherNotificationCount',String(totalNotif)); if($('teacherAdminNoticeCount')) txt('teacherAdminNoticeCount',String(adminUnread)); $('todayScheduleList').innerHTML=S.classes.map((c,i)=>`<div class="teacher-schedule-item"><div class="teacher-schedule-time">${['08:00 AM','10:00 AM','12:15 PM','02:00 PM'][i%4]}</div><div class="teacher-schedule-info"><h5>${S.t.subject} - Class ${c.class}-${c.section}</h5><p>Room ${201+i} | 45 min session</p></div></div>`).join('')||'<p style="color:var(--gray-500)">No classes assigned.</p>'; $('dashboardHomeworkList').innerHTML=h.slice(0,4).map(x=>`<div class="teacher-entry"><div class="teacher-entry-head"><div><div class="teacher-entry-title">${x.title}</div><div class="teacher-entry-sub">Class ${x.class||'--'} | Due ${fmt(x.dueDate||x.deadline)}</div></div><span class="badge ${x.submitted?'badge-green':'badge-gold'}">${x.submitted?'Submitted':'Pending'}</span></div><div class="teacher-entry-body">${x.description||x.desc||'--'}</div></div>`).join('')||'<p style="color:var(--gray-500)">No homework assigned yet.</p>'; const priorities=[]; const pendingHw=h.filter(x=>!x.submitted).slice(0,2); pendingHw.forEach(x=>priorities.push({icon:'📝',title:x.title,meta:`Class ${x.class||'--'} | Due ${fmt(x.dueDate||x.deadline)}`})); m.filter(x=>x.to===S.t.id&&!x.read).slice(0,2).forEach(x=>{const s=students().find(z=>z.id===x.from); priorities.push({icon:'💬',title:s?.name||'Unread message',meta:x.subject});}); teacherAdminNotices().slice(0,2).forEach(x=>priorities.push({icon:'📢',title:x.title,meta:`Admin notice | ${fmt(x.date||x.timestamp)}`})); getData('vm_examSchedule').filter(e=>normalizeText(e.subject)===normalizeText(S.t.subject)).slice(0,2).forEach(e=>priorities.push({icon:'📅',title:e.examName,meta:`${fmt(e.date)} | ${e.room}`})); $('teacherPriorityList').innerHTML=priorities.map(item=>`<div class="teacher-priority-item"><div class="teacher-priority-icon">${item.icon}</div><div class="teacher-priority-copy"><strong>${item.title}</strong><span>${item.meta}</span></div></div>`).join('')||'<p style="color:var(--gray-500)">No priority tasks right now.</p>';}
function renderAttendance(){const ss=byClass(S.attClass), rec=attRecord(S.attClass,S.attDate), p=Object.values(rec).filter(v=>v==='P').length, a=Object.values(rec).filter(v=>v==='A').length, u=ss.length-p-a; $('attendanceSummary').innerHTML=`<div class="teacher-mini-card"><strong>${p}</strong><span>Present</span></div><div class="teacher-mini-card"><strong>${a}</strong><span>Absent</span></div><div class="teacher-mini-card"><strong>${u}</strong><span>Unmarked</span></div>`; $('attendanceStudentList').innerHTML=ss.map(s=>{const cur=rec[s.id]||''; return `<div class="teacher-att-row"><div class="teacher-att-student"><div class="teacher-att-avatar">${s.name.charAt(0)}</div><div><strong>${s.name}</strong><div style="font-size:12px;color:var(--gray-500)">Roll ${s.rollNo||s.roll||'--'} | Class ${s.class}-${s.section}</div></div></div><div class="teacher-att-actions"><button type="button" class="teacher-att-btn ${cur==='P'?'active present':''}" onclick="tpMarkAttendance('${s.id}','P')">Present</button><button type="button" class="teacher-att-btn ${cur==='A'?'active absent':''}" onclick="tpMarkAttendance('${s.id}','A')">Absent</button></div><div style="font-size:12px;color:var(--gray-500)">${cur==='P'?'Marked present':cur==='A'?'Marked absent':'Pending mark'}</div></div>`;}).join('')||'<p style="color:var(--gray-500)">No students found for this class.</p>';}
function renderHomework(){const raw=hw().sort((a,b)=>new Date(b.dueDate||b.deadline||0)-new Date(a.dueDate||a.deadline||0)); const totalItems=raw.length, completedItems=raw.filter(x=>x.submitted).length, pendingItems=raw.filter(x=>!x.submitted).length; $('teacherHomeworkSummary').innerHTML=`<div class="teacher-mini-card"><strong>${totalItems}</strong><span>Total Assigned</span></div><div class="teacher-mini-card"><strong>${pendingItems}</strong><span>Pending</span></div><div class="teacher-mini-card"><strong>${completedItems}</strong><span>Completed</span></div>`; document.querySelectorAll('[data-hw-filter]').forEach(btn=>btn.classList.toggle('active',btn.dataset.hwFilter===S.hwFilter)); const list=raw.filter(x=>S.hwFilter==='all'||(S.hwFilter==='completed'&&x.submitted)||(S.hwFilter==='pending'&&!x.submitted)); $('teacherHomeworkList').innerHTML=list.map(x=>{const cls=byClass(x.class||''), total=cls.length||1, rels=raw.filter(r=>r.title===x.title&&r.class===x.class), sub=rels.filter(r=>r.submitted).length; return `<div class="teacher-entry"><div class="teacher-entry-head"><div><div class="teacher-entry-title">${x.title}</div><div class="teacher-entry-sub">${x.subject} | Class ${x.class||'--'} | Due ${fmt(x.dueDate||x.deadline)}</div></div><span class="badge ${sub>=total?'badge-green':'badge-gold'}">${sub}/${total} submitted</span></div><div class="teacher-entry-body">${x.description||x.desc||'--'}</div><div class="teacher-entry-meta"><span><i class="fas fa-star"></i> ${x.marks||10} marks</span><span><i class="fas fa-calendar"></i> Assigned by ${S.t.name}</span></div></div>`;}).join('')||'<p style="color:var(--gray-500)">No homework found for selected filter.</p>';}
function renderMarks(){const ss=byClass(S.marksClass), marks=getObj('vm_marks'); txt('marksSubjectLabel',`${S.t.subject} Marks`); $('teacherMarksTableBody').innerHTML=ss.map(s=>{const v=marks[s.id]?.[S.t.subject]??''; return `<tr><td>${s.rollNo||s.roll||'--'}</td><td><strong>${s.name}</strong></td><td>Class ${s.class}-${s.section}</td><td><input type="number" min="0" max="100" class="form-control tp-mark-input" data-student-id="${s.id}" value="${v}" style="max-width:100px"></td><td>${v===''?'--':grade(v)}</td></tr>`;}).join('')||'<tr><td colspan="5" style="text-align:center;color:var(--gray-500)">No students found for this class.</td></tr>';}
function convs(){const ss=students(), m=msgs().sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)), map=new Map(); m.forEach(x=>{const sid=x.from===S.t.id?x.to:x.from; if(!map.has(sid)) map.set(sid,[]); map.get(sid).push(x);}); return ss.filter(s=>map.has(s.id)).map(s=>({student:s,messages:map.get(s.id).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp))})).sort((a,b)=>new Date(b.messages.at(-1).timestamp)-new Date(a.messages.at(-1).timestamp));}
function renderMessages(){const query=normalizeText(S.msgQuery); const all=convs(); const list=all.filter(c=>!query||normalizeText(c.student.name).includes(query)||normalizeText(c.messages.at(-1).subject).includes(query)); if((!S.conv||!list.some(c=>c.student.id===S.conv))&&list[0]) S.conv=list[0].student.id; $('teacherMessageList').innerHTML=list.map(c=>`<div class="teacher-conversation-item ${S.conv===c.student.id?'active':''}" onclick="tpOpenConversation('${c.student.id}')"><div class="teacher-conversation-head"><strong>${c.student.name}</strong><span>${rel(c.messages.at(-1).timestamp)}</span></div><div class="teacher-conversation-preview">${c.messages.at(-1).subject}</div></div>`).join('')||'<p style="color:var(--gray-500)">No matching conversations.</p>'; const cur=list.find(c=>c.student.id===S.conv); if(!cur){txt('teacherMessageTitle','Message Thread'); $('teacherMessageView').innerHTML='<div class="teacher-thread-empty">Select a conversation or send a new message.</div>'; return;} txt('teacherMessageTitle',`Conversation with ${cur.student.name}`); setData('vm_messages',getData('vm_messages').map(x=>x.from===cur.student.id&&x.to===S.t.id&&!x.read?{...x,read:true}:x)); $('teacherMessageView').innerHTML=`<div class="teacher-thread">${cur.messages.map(x=>`<div class="teacher-bubble ${x.from===S.t.id?'sent':'received'}"><div class="teacher-bubble-meta"><span>${x.from===S.t.id?'You':cur.student.name}</span><span>${rel(x.timestamp)}</span></div><div>${(x.content||'').replace(/\n/g,'<br>')}</div></div>`).join('')}</div><div class="teacher-reply-box"><textarea id="tpReplyContent" class="form-control" rows="3" placeholder="Type your reply..."></textarea><button type="button" class="btn btn-primary" style="margin-top:12px" onclick="tpSendReply()">Send Reply</button></div>`; renderDash();}
function renderNotices(){const list=notices().sort((a,b)=>new Date(b.date||b.timestamp)-new Date(a.date||a.timestamp)); const adminList=teacherAdminNotices().sort((a,b)=>new Date(b.date||b.timestamp)-new Date(a.date||a.timestamp)); if($('teacherAdminNoticeMeta')) $('teacherAdminNoticeMeta').textContent=adminList[0]?`${adminList[0].title} | ${fmt(adminList[0].date||adminList[0].timestamp)}`:'No new admin message'; $('teacherNoticeList').innerHTML=list.map(n=>`<div class="teacher-entry teacher-notice-entry ${n.author==='Admin'?'admin':''}"><div class="teacher-entry-head"><div><div class="teacher-entry-title">${n.title}</div><div class="teacher-entry-sub">${n.author} | ${fmt(n.date||n.timestamp)}${n.author==='Admin'?` | ${(n.audience||'all').toUpperCase()}`:''}</div></div><div class="teacher-notice-badges"><span class="badge ${n.type==='urgent'?'badge-red':n.type==='important'?'badge-gold':'badge-primary'}">${n.type}</span>${n.author==='Admin'?'<span class="badge badge-primary">Admin</span>':''}</div></div><div class="teacher-entry-body">${n.content}</div></div>`).join('')||'<p style="color:var(--gray-500)">No notices available.</p>';}
function renderMaterials(){const m=materials(), visibleStudents=students().length, totalSize=m.list.reduce((sum,item)=>sum+parseSizeMb(item.size),0), notesCount=m.list.filter(item=>item.type==='pdf').length, videoCount=m.list.filter(item=>item.type==='mp4').length; if($('teacherMaterialHeroStats')) $('teacherMaterialHeroStats').innerHTML=`<div class="teacher-material-stat"><strong>${m.list.length}</strong><span>Total Resources</span></div><div class="teacher-material-stat"><strong>${visibleStudents}</strong><span>Visible Students</span></div><div class="teacher-material-stat"><strong>${totalSize.toFixed(1)} MB</strong><span>Library Size</span></div>`; txt('teacherMaterialResourceCount',String(m.list.length)); txt('teacherMaterialVideoCount',String(videoCount)); txt('teacherMaterialNoteCount',String(notesCount)); txt('teacherMaterialSyncMeta',`${S.t.subject} material library is linked with ${visibleStudents} student view${visibleStudents===1?'':'s'} in the portal.`); txt('teacherMaterialSubjectLabel',`Resources are currently mapped to ${S.t.subject} and sync into the student portal.`); $('teacherMaterialList').innerHTML=m.list.length?`<div class="teacher-material-library">${m.list.map(x=>`<div class="teacher-material-card"><div class="teacher-material-card-top"><div><div class="teacher-material-type ${x.type==='pdf'?'pdf':x.type==='mp4'?'mp4':'other'}"><i class="fas ${x.type==='pdf'?'fa-file-pdf':x.type==='mp4'?'fa-circle-play':'fa-book-open'}"></i>${x.type==='pdf'?'Notes Pack':x.type==='mp4'?'Video Lecture':'Resource'}</div><div class="teacher-material-title">${x.title}</div><div class="teacher-material-sub">${String(x.size||'--')} | Added ${fmt(x.createdAt||today())}</div></div><div class="teacher-material-downloads">${x.downloads||0} downloads</div></div><div class="teacher-material-meta"><span><i class="fas fa-book"></i> ${S.t.subject}</span><span><i class="fas fa-users"></i> Visible to ${visibleStudents} students</span><span><i class="fas fa-link"></i> Student portal synced</span><span><i class="fas fa-upload"></i> Added by ${x.teacherName||S.t.name}</span></div></div>`).join('')}</div>`:'<div class="teacher-material-empty"><i class="fas fa-book-open"></i><p>No study materials uploaded yet. Add your first resource and it will instantly appear in the student portal Study Material section.</p></div>';}
function drawCharts(dataset){const labels=dataset.map(item=>item.label), avgMarks=dataset.map(item=>item.avgMarks), avgAtt=dataset.map(item=>item.avgAttendance); const mc=$('teacherMarksChart'); if(mc){Chart.getChart(mc)?.destroy(); new Chart(mc,{type:'bar',data:{labels:labels.length?labels:['No Data'],datasets:[{label:`${S.t.subject} Average`,data:avgMarks.length?avgMarks:[0],backgroundColor:['#2563eb','#0f766e','#f59e0b','#8b5cf6','#ef4444'],borderRadius:10,borderSkipped:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100,grid:{color:'rgba(148, 163, 184, 0.18)'}},x:{grid:{display:false}}}}});} const ac=$('teacherAttendanceChart'); if(ac){Chart.getChart(ac)?.destroy(); new Chart(ac,{type:'doughnut',data:{labels:labels.length?labels:['No data'],datasets:[{data:avgAtt.length?avgAtt:[100],backgroundColor:['#2563eb','#10b981','#f59e0b','#ef4444','#8b5cf6'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},cutout:'66%'}});} }
function renderAnalytics(){const marks=getObj('vm_marks'), att=getObj('vm_attendance'), classes=S.analyticsClass==='all'?S.classes:S.classes.filter(c=>cLabel(c)===S.analyticsClass), dataset=classes.map(c=>{const ss=byClass(cLabel(c)), vals=ss.map(s=>Number(marks[s.id]?.[S.t.subject])).filter(Number.isFinite), avg=vals.length?(vals.reduce((a,b)=>a+b,0)/vals.length):0, avga=ss.length?Math.round(ss.reduce((a,s)=>a+(att[s.id]?.percentage||0),0)/ss.length):0, top=ss.map(s=>({s,score:Number(marks[s.id]?.[S.t.subject])||0})).sort((a,b)=>b.score-a.score)[0]; return {label:`Class ${c.class}-${c.section}`, classLabel:`${c.class}-${c.section}`, studentCount:ss.length, avgMarks:Math.round(avg), avgMarksText:vals.length?`${avg.toFixed(1)}%`:'--', avgAttendance:avga, topPerformer:top?`${top.s.name} (${top.score})`:'--', topScore:top?.score||0};}); const allStudents=students(), rankedStudents=allStudents.map(s=>({student:s,score:Number(marks[s.id]?.[S.t.subject])||0})).sort((a,b)=>b.score-a.score), topStudent=rankedStudents[0], topClass=[...dataset].sort((a,b)=>b.avgMarks-a.avgMarks)[0], attendanceLeader=[...dataset].sort((a,b)=>b.avgAttendance-a.avgAttendance)[0], overallAvg=dataset.length?Math.round(dataset.reduce((sum,item)=>sum+item.avgMarks,0)/dataset.length):0, overallAttendance=dataset.length?Math.round(dataset.reduce((sum,item)=>sum+item.avgAttendance,0)/dataset.length):0; if($('teacherAnalyticsHeroStats')) $('teacherAnalyticsHeroStats').innerHTML=`<div class="teacher-analytics-stat"><strong>${dataset.length}</strong><span>Tracked Classes</span></div><div class="teacher-analytics-stat"><strong>${overallAvg}%</strong><span>Average Score</span></div><div class="teacher-analytics-stat"><strong>${overallAttendance}%</strong><span>Average Attendance</span></div>`; txt('teacherAnalyticsTopClass',topClass?`${topClass.classLabel} • ${topClass.avgMarksText}`:'--'); txt('teacherAnalyticsAttendanceLead',attendanceLeader?`${attendanceLeader.classLabel} • ${attendanceLeader.avgAttendance}%`:'--'); txt('teacherAnalyticsTopStudent',topStudent&&topStudent.score?`${topStudent.student.name} • ${topStudent.score}`:'--'); $('teacherAnalyticsTable').innerHTML=dataset.map(item=>`<tr><td><strong>Class ${item.classLabel}</strong></td><td>${item.studentCount}</td><td>${item.avgMarksText}</td><td>${item.avgAttendance}%</td><td>${item.topPerformer}</td></tr>`).join('')||'<tr><td colspan="5" style="text-align:center;color:var(--gray-500)">No analytics data available.</td></tr>'; drawCharts(dataset);}
function renderSchedule(){const plans=lessonPlans().sort((a,b)=>new Date(a.date)-new Date(b.date)); const weekly=['Monday','Tuesday','Wednesday','Thursday','Friday']; $('teacherScheduleGrid').innerHTML=S.classes.map((c,i)=>{const key=cLabel(c), next=plans.find(plan=>plan.classLabel===key); return `<div class="teacher-schedule-item teacher-schedule-advanced"><div class="teacher-schedule-time">${['08:00 AM','09:15 AM','10:45 AM','12:00 PM','01:30 PM'][i%5]}</div><div class="teacher-schedule-info"><h5>${S.t.subject} | Class ${c.class}-${c.section}</h5><p>${weekly[i%5]} | Room ${210+i}</p><div class="teacher-schedule-focus">${next?`Next focus: ${next.topic}`:'No saved plan yet'}</div></div></div>`;}).join('')||'<p style="color:var(--gray-500)">No weekly plan available.</p>'; const ev=getData('vm_examSchedule').filter(e=>normalizeText(e.subject)===normalizeText(S.t.subject)); $('teacherEventList').innerHTML=ev.map(e=>`<div class="teacher-entry"><div class="teacher-entry-title">${e.examName}</div><div class="teacher-entry-meta"><span><i class="fas fa-calendar"></i> ${fmt(e.date)}</span><span><i class="fas fa-clock"></i> ${e.time}</span><span><i class="fas fa-map-marker-alt"></i> ${e.room}</span></div></div>`).join('')||'<p style="color:var(--gray-500)">No upcoming academic events for your subject.</p>'; const total=plans.length, nextPlan=plans.find(x=>new Date(x.date)>=new Date(today()))||plans[0], strategyCount=plans.filter(x=>x.strategy).length, assessCount=plans.filter(x=>x.assessment).length; $('teacherPlanningSummary').innerHTML=`<div class="teacher-plan-stat"><strong>${total}</strong><span>Saved Plans</span></div><div class="teacher-plan-stat"><strong>${strategyCount}</strong><span>Strategy Notes</span></div><div class="teacher-plan-stat"><strong>${assessCount}</strong><span>Assessment Blocks</span></div><div class="teacher-plan-stat"><strong>${nextPlan?fmt(nextPlan.date):'--'}</strong><span>Next Planned Class</span></div>`;}
function renderLessonPlans(){const plans=lessonPlans().sort((a,b)=>new Date(a.date)-new Date(b.date)); const recent=plans.slice(0,3); $('teacherStrategyBoard').innerHTML=recent.map(plan=>`<div class="teacher-strategy-card"><div class="teacher-strategy-top"><span class="badge badge-primary">${plan.mode||'Teaching Plan'}</span><span>${plan.duration||'45 min'}</span></div><h5>${plan.topic}</h5><p>${plan.goal||plan.objective}</p><div class="teacher-strategy-meta"><span><i class="fas fa-layer-group"></i> ${plan.classLabel}</span><span><i class="fas fa-bullseye"></i> ${plan.goal||'Lesson goal set'}</span></div></div>`).join('')||'<p style="color:var(--gray-500);margin:12px 0 18px">Create plans to build your strategy board.</p>'; $('teacherLessonPlanList').innerHTML=plans.map(plan=>`<div class="teacher-entry"><div class="teacher-entry-head"><div><div class="teacher-entry-title">${plan.topic}</div><div class="teacher-entry-sub">${fmt(plan.date)} | Class ${plan.classLabel} | ${plan.duration||'45 min'} | ${plan.mode||'Teaching plan'}</div></div><button class="btn btn-sm btn-outline-primary" type="button" onclick="tpDeleteLessonPlan('${plan.id}')">Delete</button></div><div class="teacher-entry-body"><strong>Objective:</strong> ${plan.objective}</div><div class="teacher-plan-grid"><div><strong>Goal</strong><p>${plan.goal||'Not specified'}</p></div><div><strong>Strategy</strong><p>${plan.strategy||'No strategy added'}</p></div><div><strong>Assessment</strong><p>${plan.assessment||'No assessment added'}</p></div><div><strong>Differentiation</strong><p>${plan.support||'No support plan added'}</p></div><div><strong>Success Criteria</strong><p>${plan.success||'No criteria added'}</p></div><div><strong>Resources</strong><p>${plan.resources||'No resources added'}</p></div></div></div>`).join('')||'<p style="color:var(--gray-500);margin-top:16px">No lesson plans saved yet.</p>';}
function renderSettings(){const s=settings(); $('settingEmailNotifications').checked=s.emailNotifications; $('settingParentAlerts').checked=s.parentAlerts; $('settingTaskReminders').checked=s.taskReminders;}
function renderAll(){syncTopbar();renderDash();renderAttendance();renderHomework();renderMarks();renderMessages();renderNotices();renderMaterials();renderAnalytics();renderSchedule();renderLessonPlans();renderSettings();}
async function saveAttendance(){const ss=byClass(S.attClass), rec=attRecord(S.attClass,S.attDate); if(!ss.length)return showToast('No students available for selected class.','error'); if(Object.keys(rec).length<ss.length)return showToast('Please mark attendance for all students first.','error'); const att=getObj('vm_attendance'); ss.forEach(s=>{const prev=att[s.id]||{present:0,total:0,percentage:0}, total=prev.total+1, present=prev.present+(rec[s.id]==='P'?1:0); att[s.id]={present,total,percentage:Math.round(present/total*100)};}); try{await persistTeacherKey('vm_attendance',att);}catch(error){console.warn('[Teacher] Attendance sync failed:',error);return showToast('Attendance local me save hui, lekin database sync fail ho gaya.','error');} showToast('Attendance saved successfully!','success'); renderAnalytics();}
async function saveMarks(){const exam=$('marksExamName').value.trim(), inputs=[...document.querySelectorAll('.tp-mark-input')]; if(!inputs.length)return showToast('No students available for marks entry.','error'); const marks=getObj('vm_marks'), results=getData('vm_examResults'); inputs.forEach(i=>{const sid=i.dataset.studentId, raw=i.value.trim(); if(!raw)return; const score=Math.max(0,Math.min(100,Number(raw))); if(!marks[sid])marks[sid]={}; marks[sid][S.t.subject]=score; const idx=results.findIndex(r=>r.studentId===sid&&normalizeText(r.subject)===normalizeText(S.t.subject)&&normalizeText(r.examName)===normalizeText(exam)); const entry={id:idx>-1?results[idx].id:`RES${Date.now()}${sid}`,studentId:sid,subject:S.t.subject,examName:exam||'Assessment',marks:score,maxMarks:100,percentage:score,grade:grade(score),date:today()}; if(idx>-1)results[idx]=entry; else results.push(entry);}); try{await persistTeacherKey('vm_marks',marks);await persistTeacherKey('vm_examResults',results);}catch(error){console.warn('[Teacher] Marks sync failed:',error);return showToast('Marks local me save hue, lekin database sync fail ho gaya.','error');} showToast('Marks saved successfully!','success'); renderMarks(); renderDash(); renderAnalytics();}
async function publishNotice(form){const title=$('tpNoticeTitle').value.trim(), content=$('tpNoticeContent').value.trim(), type=$('tpNoticeType').value; if(!title||!content)return showToast('Please fill in title and content.','error'); const list=getData('vm_notices'); list.unshift({id:`N${Date.now()}`,title,content,date:today(),type,author:S.t.name,category:'classroom'}); try{await persistTeacherKey('vm_notices',list);}catch(error){console.warn('[Teacher] Notice sync failed:',error);return showToast('Notice local me save hui, lekin database sync fail ho gaya.','error');} form.reset(); tpCloseModal('tpNoticeModal'); renderNotices(); showToast('Notice published successfully!','success');}
async function saveMaterial(form){const title=$('tpMaterialTitle').value.trim(), type=$('tpMaterialType').value, size=$('tpMaterialSize').value.trim(); if(!title||!size)return showToast('Please complete material details.','error'); const m=materials(); if(!m.all[m.key])m.all[m.key]=[]; m.all[m.key].unshift({id:`MAT${Date.now()}`,title,type,size,downloads:0,createdAt:today(),teacherName:S.t.name,subject:S.t.subject}); try{await persistTeacherKey('vm_studyMaterials',m.all);}catch(error){console.warn('[Teacher] Material sync failed:',error);return showToast('Material local me save hua, lekin database sync fail ho gaya.','error');} form.reset(); tpCloseModal('tpMaterialModal'); renderMaterials(); showToast('Material saved successfully! Student portal sync updated.','success');}
async function assignHomework(form){const cls=$('tpHomeworkClass').value, title=$('tpHomeworkTitle').value.trim(), desc=$('tpHomeworkDescription').value.trim(), due=$('tpHomeworkDueDate').value, marks=Number($('tpHomeworkMarks').value)||10; if(!cls||!title||!desc||!due)return showToast('Please complete all homework fields.','error'); const ss=byClass(cls); if(!ss.length)return showToast('No students found for selected class.','error'); const list=getData('vm_homework'); ss.forEach(s=>list.unshift({id:`HW${Date.now()}${s.id}`,studentId:s.id,class:cls,subject:S.t.subject,title,description:desc,dueDate:due,marks,teacher:S.t.name,teacherId:S.t.id,status:'pending',submitted:false})); try{await persistTeacherKey('vm_homework',list);}catch(error){console.warn('[Teacher] Homework sync failed:',error);return showToast('Homework local me assign hua, lekin database sync fail ho gaya.','error');} form.reset(); tpCloseModal('tpHomeworkModal'); renderHomework(); renderDash(); showToast(`Homework assigned to ${ss.length} students.`,'success');}
async function sendMessage(form){const sid=$('tpMessageStudent').value, sub=$('tpMessageSubject').value.trim(), content=$('tpMessageContent').value.trim(); if(!sid||!sub||!content)return showToast('Please complete all message fields.','error'); const list=getData('vm_messages'); list.push({id:`MSG${Date.now()}`,from:S.t.id,to:sid,subject:sub,content,timestamp:new Date().toISOString(),read:false,type:'sent'}); try{await persistTeacherKey('vm_messages',list);}catch(error){console.warn('[Teacher] Message sync failed:',error);return showToast('Message local me save hua, lekin database sync fail ho gaya.','error');} form.reset(); tpCloseModal('tpMessageModal'); S.conv=sid; renderMessages(); renderDash(); showToast('Message sent successfully!','success');}
async function sendReply(){const content=$('tpReplyContent')?.value.trim(); if(!S.conv||!content)return showToast('Please type a reply first.','error'); const list=getData('vm_messages'); list.push({id:`MSG${Date.now()}`,from:S.t.id,to:S.conv,subject:`Re: ${S.t.subject}`,content,timestamp:new Date().toISOString(),read:false,type:'sent'}); try{await persistTeacherKey('vm_messages',list);}catch(error){console.warn('[Teacher] Reply sync failed:',error);return showToast('Reply local me save hui, lekin database sync fail ho gaya.','error');} renderMessages(); showToast('Reply sent successfully!','success');}
async function saveSettingValues(){const next={emailNotifications:$('settingEmailNotifications').checked,parentAlerts:$('settingParentAlerts').checked,taskReminders:$('settingTaskReminders').checked}; const all=getObj('vm_teacherSettings');all[S.t.id]=next; try{await persistTeacherKey('vm_teacherSettings',all);}catch(error){console.warn('[Teacher] Settings sync failed:',error);return showToast('Settings local me save hui, lekin database sync fail ho gaya.','error');} showToast('Teacher settings saved!','success');}
async function saveLessonPlan(form){const date=$('tpLessonDate').value, classLabel=$('tpLessonClass').value, topic=$('tpLessonTopic').value.trim(), goal=$('tpLessonGoal').value.trim(), duration=$('tpLessonDuration').value, mode=$('tpLessonMode').value, objective=$('tpLessonObjective').value.trim(), resources=$('tpLessonResources').value.trim(), strategy=$('tpLessonStrategy').value.trim(), assessment=$('tpLessonAssessment').value.trim(), support=$('tpLessonSupport').value.trim(), success=$('tpLessonSuccess').value.trim(); if(!date||!classLabel||!topic||!goal||!objective||!strategy||!assessment)return showToast('Please complete the planning form first.','error'); const plans=lessonPlans(); plans.unshift({id:`LP${Date.now()}`,date,classLabel,topic,goal,duration,mode,objective,resources,strategy,assessment,support,success}); const all=getObj('vm_teacherLessonPlans');all[S.t.id]=plans; try{await persistTeacherKey('vm_teacherLessonPlans',all);}catch(error){console.warn('[Teacher] Lesson plan sync failed:',error);return showToast('Lesson plan local me save hua, lekin database sync fail ho gaya.','error');} form.reset(); $('tpLessonDate').value=today(); if($('tpLessonDuration')) $('tpLessonDuration').value='45 min'; if($('tpLessonMode')) $('tpLessonMode').value='Interactive board teaching'; renderSchedule(); renderLessonPlans(); showToast('Teaching plan saved successfully!','success');}
function applyPlanningTemplate(){const subject=S.t.subject||'Subject'; const first=S.classes[0]?cLabel(S.classes[0]):''; if($('tpLessonClass')&&first&&!$('tpLessonClass').value) $('tpLessonClass').value=first; if($('tpLessonTopic')&&!$('tpLessonTopic').value) $('tpLessonTopic').value=`${subject} guided practice`; if($('tpLessonGoal')&&!$('tpLessonGoal').value) $('tpLessonGoal').value='Concept clarity and confident application'; if($('tpLessonObjective')&&!$('tpLessonObjective').value) $('tpLessonObjective').value=`Students will understand the key ${subject.toLowerCase()} concept and apply it in guided and independent practice.`; if($('tpLessonResources')&&!$('tpLessonResources').value) $('tpLessonResources').value='Board explanation, worksheet, PPT recap, peer discussion prompts'; if($('tpLessonStrategy')&&!$('tpLessonStrategy').value) $('tpLessonStrategy').value='Start with quick recap, model examples, pair discussion, guided practice, and final summary check.'; if($('tpLessonAssessment')&&!$('tpLessonAssessment').value) $('tpLessonAssessment').value='Use oral questioning, one exit ticket, and notebook review for understanding.'; if($('tpLessonSupport')&&!$('tpLessonSupport').value) $('tpLessonSupport').value='Give scaffold steps to struggling learners and challenge questions to advanced students.'; if($('tpLessonSuccess')&&!$('tpLessonSuccess').value) $('tpLessonSuccess').value='Students can explain the concept and solve at least one question independently.'; showToast('Planning template applied. You can now customize it.','success');}
function exportAnalytics(){const rows=[['Class','Students','Average Marks','Attendance','Top Performer']]; document.querySelectorAll('#teacherAnalyticsTable tr').forEach(tr=>{const cols=[...tr.querySelectorAll('td')].map(td=>td.textContent.trim()); if(cols.length) rows.push(cols);}); const csv=rows.map(r=>r.map(v=>`\"${v}\"`).join(',')).join('\\n'); const blob=new Blob([csv],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`teacher-analytics-${Date.now()}.csv`; a.click(); showToast('Analytics report exported.','success');}
function bind(){document.querySelectorAll('.portal-nav a[data-section]').forEach(a=>a.addEventListener('click',()=>openSection(a.dataset.section))); $('teacherSidebarToggle').addEventListener('click',()=>$('teacherSidebar').classList.toggle('open')); $('attendanceClassSelect').addEventListener('change',e=>{S.attClass=e.target.value;renderAttendance();}); $('attendanceDate').addEventListener('change',e=>{S.attDate=e.target.value;renderAttendance();}); $('marksClassSelect').addEventListener('change',e=>{S.marksClass=e.target.value;renderMarks();}); $('analyticsClassSelect')?.addEventListener('change',e=>{S.analyticsClass=e.target.value;renderAnalytics();}); $('teacherMessageSearch')?.addEventListener('input',e=>{S.msgQuery=e.target.value;renderMessages();}); $('tpHomeworkForm').addEventListener('submit',e=>{e.preventDefault();assignHomework(e.target);}); $('tpMessageForm').addEventListener('submit',e=>{e.preventDefault();sendMessage(e.target);}); $('tpNoticeForm').addEventListener('submit',e=>{e.preventDefault();publishNotice(e.target);}); $('tpMaterialForm').addEventListener('submit',e=>{e.preventDefault();saveMaterial(e.target);}); $('tpLessonPlanForm')?.addEventListener('submit',e=>{e.preventDefault();saveLessonPlan(e.target);});}
async function init(){if(window.ensureVmDataReady){await window.ensureVmDataReady();}else{seedData();} S.t=tUser(); if(!S.t){window.location.href='../pages/login.html';return;} S.classes=parseClasses(S.t.class); S.attDate=today(); ensureTeacherDemoData(); fillSelectors(); fillMessageStudents(); bind(); renderAll(); openSection('secDash');}
window.tpNavigate=openSection;
window.tpMarkAttendance=function(id,status){const rec=attRecord(S.attClass,S.attDate); rec[id]=status; setAttRecord(S.attClass,S.attDate,rec); renderAttendance();};
window.tpSaveAttendance=saveAttendance;
window.tpSaveMarks=saveMarks;
window.tpOpenConversation=function(id){S.conv=id; renderMessages(); renderDash();};
window.tpSendReply=sendReply;
window.tpSaveSettings=saveSettingValues;
window.tpSetHomeworkFilter=function(filter){S.hwFilter=filter; renderHomework();};
window.tpExportAnalytics=exportAnalytics;
window.tpApplyPlanningTemplate=applyPlanningTemplate;
window.tpDeleteLessonPlan=async function(id){const plans=lessonPlans().filter(plan=>plan.id!==id); const all=getObj('vm_teacherLessonPlans');all[S.t.id]=plans; try{await persistTeacherKey('vm_teacherLessonPlans',all);}catch(error){console.warn('[Teacher] Lesson plan delete sync failed:',error);return showToast('Lesson plan delete local me hua, lekin database sync fail ho gaya.','error');} renderSchedule(); renderLessonPlans(); showToast('Lesson plan removed.','success');};
window.tpOpenModal=id=>$(id)?.classList.add('show');
window.tpCloseModal=id=>$(id)?.classList.remove('show');
window.tpOpenHomeworkModal=()=>{if($('tpHomeworkClass')) $('tpHomeworkClass').value=S.attClass||S.marksClass||''; tpOpenModal('tpHomeworkModal');};
window.tpOpenMessageModal=()=>{fillMessageStudents(); tpOpenModal('tpMessageModal');};
window.tpOpenNoticeModal=()=>tpOpenModal('tpNoticeModal');
window.tpOpenMaterialModal=()=>tpOpenModal('tpMaterialModal');
document.addEventListener('DOMContentLoaded',init);
})();
